In [9]:
import pandas as pd

# Inspection

In [11]:
orders = pd.read_csv(
    "olist_ecommerce_datasets/olist_orders_dataset.csv"
)

items = pd.read_csv(
    "olist_ecommerce_datasets/olist_order_items_dataset.csv"
)

products = pd.read_csv(
    "olist_ecommerce_datasets/olist_products_dataset.csv"
)

sellers = pd.read_csv(
    "olist_ecommerce_datasets/olist_sellers_dataset.csv"
)

customers = pd.read_csv(
    "olist_ecommerce_datasets/olist_customers_dataset.csv"
)

payments = pd.read_csv(
    "olist_ecommerce_datasets/olist_order_payments_dataset.csv"
)

for name, df in {
    "orders": orders,
    "items": items,
    "products": products,
    "sellers": sellers,
    "customers": customers,
    "payments": payments,
}.items():
    print(f"\n{name.upper()}")
    print(df.shape)
    display(df.info())

ORDERS
(99441, 8)
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

None

ITEMS
(112650, 7)
<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

None

PRODUCTS
(32951, 9)
<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

None

SELLERS
(3095, 4)
<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB

None

CUSTOMERS
(99441, 5)
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

None

PAYMENTS
(103886, 5)
<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

None

In [12]:
print("Orders")
print("Rows:", len(orders))
print("Unique order IDs:", orders["order_id"].nunique())
print("Unique customer IDs:", orders["customer_id"].nunique())

print("\nItems")
print("Rows:", len(items))
print("Unique order IDs:", items["order_id"].nunique())
print("Unique product IDs:", items["product_id"].nunique())
print("Unique seller IDs:", items["seller_id"].nunique())

print("\nProducts")
print("Rows:", len(products))
print("Unique product IDs:", products["product_id"].nunique())

print("\nSellers")
print("Rows:", len(sellers))
print("Unique seller IDs:", sellers["seller_id"].nunique())

print("\nCustomers")
print("Rows:", len(customers))
print("Unique customer IDs:", customers["customer_id"].nunique())
print("Unique customer unique IDs:", customers["customer_unique_id"].nunique())

print("\nPayments")
print("Rows:", len(payments))
print("Unique order IDs:", payments["order_id"].nunique())

Orders
Rows: 99441
Unique order IDs: 99441
Unique customer IDs: 99441

Items
Rows: 112650
Unique order IDs: 98666
Unique product IDs: 32951
Unique seller IDs: 3095

Products
Rows: 32951
Unique product IDs: 32951

Sellers
Rows: 3095
Unique seller IDs: 3095

Customers
Rows: 99441
Unique customer IDs: 99441
Unique customer unique IDs: 96096

Payments
Rows: 103886
Unique order IDs: 99440

In [13]:
items_per_order = items.groupby("order_id").size()
sellers_per_order = items.groupby("order_id")["seller_id"].nunique()
products_per_order = items.groupby("order_id")["product_id"].nunique()
payments_per_order = payments.groupby("order_id").size()

print("Items per order")
display(items_per_order.describe())

print("\nSellers per order")
display(sellers_per_order.value_counts().sort_index())

print("\nProducts per order")
display(products_per_order.describe())

print("\nPayments per order")
display(payments_per_order.value_counts().sort_index())

Items per order

count    98666.000000
mean         1.141731
std          0.538452
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         21.000000
dtype: float64

Sellers per order

seller_id
1    97388
2     1219
3       54
4        3
5        2
Name: count, dtype: int64

Products per order

count    98666.000000
mean         1.038098
std          0.226456
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          8.000000
Name: product_id, dtype: float64

Payments per order

1     96479
2      2382
3       301
4       108
5        52
6        36
7        28
8        11
9         9
10        5
11        8
12        8
13        3
14        2
15        2
19        2
21        1
22        1
26        1
29        1
Name: count, dtype: int64

In [14]:
date_cols = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date",
]

orders[date_cols] = orders[date_cols].apply(pd.to_datetime)

items["shipping_limit_date"] = pd.to_datetime(
    items["shipping_limit_date"]
)

In [15]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [16]:
timestamp_cols = [
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date",
]

missing_by_status = (
    orders.groupby("order_status")[timestamp_cols]
    .agg(lambda x: x.isna().mean())
    .round(3)
)

display(missing_by_status)

,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
order_status,,,,
approved,0.000,1.00,1.00,0.0
canceled,0.226,0.88,0.99,0.0
created,1.000,1.00,1.00,0.0
delivered,0.000,0.00,0.00,0.0
invoiced,0.000,1.00,1.00,0.0
processing,0.000,1.00,1.00,0.0
shipped,0.000,0.00,1.00,0.0
unavailable,0.000,1.00,1.00,0.0

In [17]:
delivered = orders.loc[
    orders["order_status"] == "delivered"
].copy()

delivered["approval_hours"] = (
    delivered["order_approved_at"]
    - delivered["order_purchase_timestamp"]
).dt.total_seconds() / 3600

delivered["seller_to_carrier_days"] = (
    delivered["order_delivered_carrier_date"]
    - delivered["order_approved_at"]
).dt.total_seconds() / 86400

delivered["carrier_to_customer_days"] = (
    delivered["order_delivered_customer_date"]
    - delivered["order_delivered_carrier_date"]
).dt.total_seconds() / 86400

delivered["total_delivery_days"] = (
    delivered["order_delivered_customer_date"]
    - delivered["order_purchase_timestamp"]
).dt.total_seconds() / 86400

display(
    delivered[
        [
            "approval_hours",
            "seller_to_carrier_days",
            "carrier_to_customer_days",
            "total_delivery_days",
        ]
    ].describe()
)

,approval_hours,seller_to_carrier_days,carrier_to_customer_days,total_delivery_days
count,96464.000000,96462.000000,96469.000000,96470.000000
mean,10.276767,2.799076,9.330297,12.558217
std,20.535419,3.537077,8.759924,9.546156
min,0.000000,-171.219005,-16.096169,0.533414
25%,0.215278,0.874363,4.100046,6.766204
50%,0.343333,1.815845,7.099769,10.217477
75%,14.514583,3.575009,12.028646,15.720182
max,741.443611,125.762569,205.190972,209.628611

In [18]:
anomalies = pd.Series({
    "approval_before_purchase": (
        delivered["order_approved_at"]
        < delivered["order_purchase_timestamp"]
    ).sum(),

    "carrier_before_approval": (
        delivered["order_delivered_carrier_date"]
        < delivered["order_approved_at"]
    ).sum(),

    "delivery_before_carrier": (
        delivered["order_delivered_customer_date"]
        < delivered["order_delivered_carrier_date"]
    ).sum(),

    "delivery_before_purchase": (
        delivered["order_delivered_customer_date"]
        < delivered["order_purchase_timestamp"]
    ).sum(),
})

display(anomalies)

approval_before_purchase       0
carrier_before_approval     1350
delivery_before_carrier       23
delivery_before_purchase       0
dtype: int64

In [ ]:
olist_df = (
    items
    .merge(
        orders,
        on="order_id",
        how="left",
        validate="many_to_one",
    )
    .merge(
        products,
        on="product_id",
        how="left",
        validate="many_to_one",
    )
    .merge(
        sellers,
        on="seller_id",
        how="left",
        validate="many_to_one",
    )
    .merge(
        customers,
        on="customer_id",
        how="left",
        validate="many_to_one",
    )
)

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 29 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       112650 non-null  str
 1   order_item_id                  112650 non-null  int64
 2   product_id                     112650 non-null  str
 3   seller_id                      112650 non-null  str
 4   shipping_limit_date            112650 non-null  datetime64[us]
 5   price                          112650 non-null  float64
 6   freight_value                  112650 non-null  float64
 7   customer_id                    112650 non-null  str
 8   order_status                   112650 non-null  str
 9   order_purchase_timestamp       112650 non-null  datetime64[us]
 10  order_approved_at              112635 non-null  datetime64[us]
 11  order_delivered_carrier_date   111456 non-null  datetime64[us]
 12  order_delivered_customer_date  110196 non-null  datetime64[us]
 13  order_estimated_delivery_date  112650 non-null  datetime64[us]
 14  product_category_name          111047 non-null  str
 15  product_name_lenght            111047 non-null  float64
 16  product_description_lenght     111047 non-null  float64
 17  product_photos_qty             111047 non-null  float64
 18  product_weight_g               112632 non-null  float64
 19  product_length_cm              112632 non-null  float64
 20  product_height_cm              112632 non-null  float64
 21  product_width_cm               112632 non-null  float64
 22  seller_zip_code_prefix         112650 non-null  int64
 23  seller_city                    112650 non-null  str
 24  seller_state                   112650 non-null  str
 25  customer_unique_id             112650 non-null  str
 26  customer_zip_code_prefix       112650 non-null  int64
 27  customer_city                  112650 non-null  str
 28  customer_state                 112650 non-null  str
dtypes: datetime64[us](6), float64(9), int64(3), str(11)
memory usage: 24.9 MB

In [ ]:
payment_summary = (
    payments.groupby("order_id")
    .agg(
        payment_value=("payment_value", "sum"),
        payment_installments=("payment_installments", "max"),
        payment_count=("payment_sequential", "count"),
        payment_type_count=("payment_type", "nunique"),
    )
    .reset_index()
)

,order_id,payment_value,payment_installments,payment_count,payment_type_count
0,00010242fe8c5a6d1ba2dd792cb16214,72.19,2,1,1
1,00018f77f2f0320c557190d7a144bdd3,259.83,3,1,1
2,000229ec398224ef6ca0657da4fc703e,216.87,5,1,1
3,00024acbcdf0a6daa1e931b038114c75,25.78,2,1,1
4,00042b26cf59d7ce69dfabb4e55b4fd9,218.04,3,1,1
...,...,...,...,...,...
99435,fffc94f6ce00a00581880bf54a75a037,343.40,1,1,1
99436,fffcd46ef2263f404302a634eb57f7eb,386.53,1,1,1
99437,fffce4705a9662cd70adb13d4a31832d,116.85,3,1,1
99438,fffe18544ffabc95dfada21779c9644f,64.71,3,1,1
99439,fffe41c64501cc87c801fd61db3f6244,55.79,1,1,1

In [23]:
primary_payment = (
    payments.loc[
        payments.groupby("order_id")["payment_value"].idxmax(),
        ["order_id", "payment_type"],
    ]
    .rename(columns={"payment_type": "primary_payment_type"})
)

payment_summary = payment_summary.merge(
    primary_payment,
    on="order_id",
    how="left",
    validate="one_to_one",
)

In [24]:
olist_df = olist_df.merge(
    payment_summary,
    on="order_id",
    how="left",
    validate="many_to_one",
)

In [25]:
print("Shape:", olist_df.shape)
print("Unique orders:", olist_df["order_id"].nunique())
print("Unique sellers:", olist_df["seller_id"].nunique())
print("Unique products:", olist_df["product_id"].nunique())

olist_df.info()

Shape: (112650, 34)
Unique orders: 98666
Unique sellers: 3095
Unique products: 32951
<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 34 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       112650 non-null  str
 1   order_item_id                  112650 non-null  int64
 2   product_id                     112650 non-null  str
 3   seller_id                      112650 non-null  str
 4   shipping_limit_date            112650 non-null  datetime64[us]
 5   price                          112650 non-null  float64
 6   freight_value                  112650 non-null  float64
 7   customer_id                    112650 non-null  str
 8   order_status                   112650 non-null  str
 9   order_purchase_timestamp       112650 non-null  datetime64[us]
 10  order_approved_at              112635 non-null  datetime64[us]
 11  order_delivered_carrier_date   111456 non-null  datetime64[us]
 12  order_delivered_customer_date  110196 non-null  datetime64[us]
 13  order_estimated_delivery_date  112650 non-null  datetime64[us]
 14  product_category_name          111047 non-null  str
 15  product_name_lenght            111047 non-null  float64
 16  product_description_lenght     111047 non-null  float64
 17  product_photos_qty             111047 non-null  float64
 18  product_weight_g               112632 non-null  float64
 19  product_length_cm              112632 non-null  float64
 20  product_height_cm              112632 non-null  float64
 21  product_width_cm               112632 non-null  float64
 22  seller_zip_code_prefix         112650 non-null  int64
 23  seller_city                    112650 non-null  str
 24  seller_state                   112650 non-null  str
 25  customer_unique_id             112650 non-null  str
 26  customer_zip_code_prefix       112650 non-null  int64
 27  customer_city                  112650 non-null  str
 28  customer_state                 112650 non-null  str
 29  payment_value                  112647 non-null  float64
 30  payment_installments           112647 non-null  float64
 31  payment_count                  112647 non-null  float64
 32  payment_type_count             112647 non-null  float64
 33  primary_payment_type           112647 non-null  str
dtypes: datetime64[us](6), float64(13), int64(3), str(12)
memory usage: 29.2 MB

### Export consolidated dataset

In [26]:
olist_df.to_csv(
    "olist_ecommerce_datasets/olist_consolidated.csv",
    index=False,
)

# EDA

In [27]:
fulfillment = olist_df.dropna(
    subset=[
        "order_delivered_carrier_date",
        "shipping_limit_date",
    ]
).copy()

fulfillment["missed_shipping_deadline"] = (
    fulfillment["order_delivered_carrier_date"]
    > fulfillment["shipping_limit_date"]
)

print("Eligible rows:", len(fulfillment))
display(
    fulfillment["missed_shipping_deadline"]
    .value_counts()
    .to_frame("count")
    .assign(
        percent=lambda x: (
            x["count"] / x["count"].sum() * 100
        ).round(2)
    )
)

Eligible rows: 111456

                           count  percent
missed_shipping_deadline
False                     101033    90.65
True                       10423     9.35

In [28]:
fulfillment["allowed_fulfillment_days"] = (
    fulfillment["shipping_limit_date"]
    - fulfillment["order_approved_at"]
).dt.total_seconds() / 86400

fulfillment["allowed_fulfillment_days"].describe()

count    111441.000000
mean          6.174684
std           6.269024
min          -6.400498
25%           4.000000
50%           6.000000
75%           6.000000
max        1056.041667
Name: allowed_fulfillment_days, dtype: float64

In [29]:
fulfillment["allowed_fulfillment_days"].round().value_counts().sort_index()

allowed_fulfillment_days
-6.0       11
-5.0        7
-4.0        3
-3.0       16
-2.0       16
           ..
 73.0       1
 93.0       1
 97.0       1
 1051.0     2
 1056.0     1
Name: count, Length: 62, dtype: int64

In [30]:
delivered_fulfillment = fulfillment.loc[
    fulfillment["order_status"] == "delivered"
].copy()

delivered_fulfillment["late_customer_delivery"] = (
    delivered_fulfillment["order_delivered_customer_date"]
    > delivered_fulfillment["order_estimated_delivery_date"]
)

display(
    pd.crosstab(
        delivered_fulfillment["missed_shipping_deadline"],
        delivered_fulfillment["late_customer_delivery"],
        normalize="index",
    ).round(3)
)

late_customer_delivery    False  True
missed_shipping_deadline
False                     0.938  0.062
True                      0.759  0.241

In [31]:
seller_performance = (
    fulfillment.groupby("seller_id")
    .agg(
        orders=("order_id", "nunique"),
        miss_rate=("missed_shipping_deadline", "mean"),
    )
)

display(
    seller_performance.loc[
        seller_performance["orders"] >= 20
    ]["miss_rate"].describe()
)

count    811.000000
mean       0.091113
std        0.116887
min        0.000000
25%        0.012579
50%        0.047619
75%        0.120606
max        0.823529
Name: miss_rate, dtype: float64

In [32]:
fulfillment["purchase_month"] = (
    fulfillment["order_purchase_timestamp"]
    .dt.to_period("M")
)

monthly_miss_rate = (
    fulfillment.groupby("purchase_month")[
        "missed_shipping_deadline"
    ]
    .agg(["count", "mean"])
)

display(monthly_miss_rate)

                count      mean
purchase_month
2016-09             5  0.600000
2016-10           327  0.495413
2016-12             1  0.000000
2017-01           931  0.221267
2017-02          1881  0.181287
2017-03          2945  0.075382
2017-04          2626  0.072353
2017-05          4062  0.074101
2017-06          3540  0.081921
2017-07          4474  0.086723
2017-08          4839  0.069642
2017-09          4774  0.077084
2017-10          5250  0.078857
2017-11          8552  0.132834
2017-12          6247  0.112374
2018-01          8146  0.107292
2018-02          7624  0.132476
2018-03          8161  0.086386
2018-04          7932  0.061901
2018-05          7867  0.063684
2018-06          7056  0.068452
2018-07          7024  0.091259
2018-08          7191  0.091503
2018-09             1  0.000000